/**
 * A Markdown or MDX Page
 */

import { action, computed, observable, ObservableMap } from 'mobx';
import { AUTO_GENERATED_PAGE_PREFIX, PageStore } from '@tdev-stores/PageStore';
import _ from 'es-toolkit/compat';
import iDocument from '@tdev-models/iDocument';
import StudentGroup from '@tdev-models/StudentGroup';
import { DocumentType } from '@tdev-api/document';
import { iTaskableDocument } from './iTaskableDocument';
import { mdiCheckCircleOutline, mdiSpeedometer, mdiSpeedometerMedium, mdiSpeedometerSlow } from '@mdi/js';
import { IfmColors } from '@tdev-components/shared/Colors';
interface PageConfig {
    type: DocumentType;
    position: number;
}

export default class Page {
    readonly store: PageStore;
    readonly id: string;
    readonly path: string;
    initialLoadComplete = false;

    @observable.ref accessor _primaryStudentGroupName: string | undefined = undefined;
    @observable.ref accessor _activeStudentGroup: StudentGroup | undefined = undefined;
    documentRootConfigs: ObservableMap<string, PageConfig>;

    dynamicValues = observable.map<string, string>();

    constructor(id: string, path: string, store: PageStore) {
        this.id = id;
        this.path = path;
        this.store = store;
        this.documentRootConfigs = observable.map<string, PageConfig>(
            this.isAutoGenerated ? [] : [[id, { type: 'mdx_comment', position: 0 }]],
            { deep: false }
        );
    }

    @computed
    get isAutoGenerated() {
        return this.id.startsWith(AUTO_GENERATED_PAGE_PREFIX);
    }

    @computed
    get isLandingpage() {
        return this.store.sidebarVersions.some((version) => version.rootPaths.includes(this.path));
    }

    @computed
    get parentPath() {
        const parts = this.path.split('/').slice(0, -2);
        while (parts.length > 1) {
            const parentPath = `${parts.join('/')}/`;
            const parentPage = this.store.pages.find((p) => p.path === parentPath);
            if (parentPage) {
                return parentPage.path;
            }
            if (this.store.sidebarVersions.some((v) => v.versionPath === parentPath)) {
                return parentPath;
            }
            parts.splice(-1, 1);
        }
        return '/';
    }

    @computed
    get subPages() {
        return this.store.pages.filter((page) => page.parentPath === this.path);
    }

    @action
    setDynamicValue(key: string, value?: string) {
        if (value === undefined) {
            this.dynamicValues.delete(key);
            return;
        }
        this.dynamicValues.set(key, value);
    }

    @action
    assertDocumentRoot(doc: iDocument<any>) {
        if (process.env.NODE_ENV === 'production') {
            return;
        }
        if (!this.documentRootConfigs.has(doc.documentRootId)) {
            this.store.loadPageIndex(true);
        }
    }

    @action
    addDocumentRootConfig(id: string, config: PageConfig) {
        this.documentRootConfigs.set(id, { type: config.type, position: config.position });
    }

    @computed
    get documentRoots() {
        return this.store.root.documentRootStore.documentRoots
            .filter((doc) => this.documentRootConfigs.has(doc.id) && !doc.isDummy)
            .sort((a, b) => {
                const pA = this.documentRootConfigs.get(a.id)!.position;
                const pB = this.documentRootConfigs.get(b.id)!.position;
                return pA - pB;
            });
    }

    @computed
    get documents() {
        return this.documentRoots
            .flatMap((doc) => doc.firstMainDocument)
            .filter((d) => d?.root?.meta.pagePosition)
            .sort((a, b) => a!.root!.meta!.pagePosition - b!.root!.meta.pagePosition);
    }

    @computed
    get primaryStudentGroupName() {
        return this._primaryStudentGroupName ?? this.store.currentStudentGroupName;
    }

    @action
    setPrimaryStudentGroupName(name?: string) {
        this._primaryStudentGroupName = name;
    }

    get hasCustomPrimaryStudentGroup() {
        return !!this._primaryStudentGroupName;
    }

    @computed
    get primaryStudentGroup() {
        return this._primaryStudentGroupName
            ? this.store.root.studentGroupStore.findByName(this._primaryStudentGroupName)
            : undefined;
    }

    @action
    setPrimaryStudentGroup(group?: StudentGroup) {
        if (
            group &&
            (group.id === this.primaryStudentGroup?.id ||
                this._activeStudentGroup?.parentIds.includes(group.id))
        ) {
            this.setPrimaryStudentGroupName(undefined);
            this._activeStudentGroup = undefined;
            return;
        }
        this.setPrimaryStudentGroupName(group?.name);
        if (group) {
            this._activeStudentGroup = undefined;
        }
    }

    /**
     * loads all linked document roots (added by #addDocumentRoot)
     */
    @action
    loadLinkedDocumentRoots(force = false) {
        if (!force && !this.store.root.userStore.isUserSwitched) {
            return;
        }
        if (!force && this.initialLoadComplete) {
            return;
        }
        this.initialLoadComplete = true;
        return this.store.loadAllDocuments(this);
    }

    get TaskableDocuments() {
        return this.store.root.componentStore.taskableDocuments;
    }

    @computed
    get taskableDocumentRootIds() {
        return [...this.documentRootConfigs.keys()].filter((id) => {
            const config = this.documentRootConfigs.get(id)!;
            return this.TaskableDocuments.has(config.type);
        });
    }

    @computed
    get taskableDocuments(): iTaskableDocument[] {
        const uid = this.store.root.userStore.viewedUserId;
        if (!uid) {
            return [];
        }
        return this.taskableDocumentRootIds.flatMap((rid) => {
            return this.store.root.documentStore
                .findByDocumentRoot(rid)
                .filter(
                    (doc) => doc.authorId === uid && this.TaskableDocuments.has(doc.type)
                ) as iTaskableDocument[];
        });
    }

    @computed
    get stepsOnPage(): number {
        return this.taskableDocuments.length;
    }

    @computed
    get stepsOnDirectSubPages(): number {
        return this.subPages.reduce((sum, page) => sum + page.stepsOnPage, 0);
    }

    @computed
    get totalSteps(): number {
        return this.stepsOnPage + this.subPages.reduce((sum, page) => sum + page.totalSteps, 0);
    }

    @computed
    get progress(): number {
        return (
            this.taskableDocuments.filter((d) => d.isDone).length +
            this.subPages.reduce((sum, page) => sum + page.progress, 0)
        );
    }

    @computed
    get isDone(): boolean {
        return this.progress > 0 && this.progress >= this.totalSteps;
    }

    @computed
    get editingIconState() {
        if (this.isDone) {
            return { path: mdiCheckCircleOutline, color: IfmColors.green };
        }
        const level = this.progress / this.totalSteps;
        if (this.progress === 0) {
            return { path: mdiSpeedometerSlow, color: IfmColors.gray };
        }
        if (level < 1 / 3) {
            return { path: mdiSpeedometerSlow, color: IfmColors.red };
        }
        if (level < 2 / 3) {
            return { path: mdiSpeedometerMedium, color: IfmColors.orange };
        }
        return { path: mdiSpeedometer, color: IfmColors.lightGreen };
    }

    @computed
    get editingState(): iTaskableDocument[] {
        return this.taskableDocuments;
    }

    @action
    toggleActiveStudentGroup(studentGroup: StudentGroup) {
        if (this._activeStudentGroup && this._activeStudentGroup.id === studentGroup.id) {
            this._activeStudentGroup = undefined;
        } else {
            this._activeStudentGroup = studentGroup;
        }
    }

    @computed
    get childStudentGroups() {
        if (this.primaryStudentGroup) {
            return this.primaryStudentGroup.children;
        }
        return _.orderBy(
            this.store.root.studentGroupStore.managedStudentGroups.filter((sg) => !!sg.parentId),
            ['name'],
            ['asc']
        );
    }

    @computed
    get activeStudentGroup() {
        return this._activeStudentGroup || this.primaryStudentGroup;
    }

    @computed
    get editingStateByUsers() {
        return _.groupBy(
            this.taskableDocumentRootIds
                .flatMap((rid) => {
                    return this.store.root.documentStore
                        .findByDocumentRoot(rid)
                        .filter((doc) => this.TaskableDocuments.has(doc.type)) as iTaskableDocument[];
                })
                .filter((doc) =>
                    this.activeStudentGroup ? this.activeStudentGroup.userIds.has(doc.authorId) : true
                ),
            (doc) => doc.authorId
        );
    }

    @computed
    get userIdsWithoutEditingState(): string[] {
        const editingStates = this.editingStateByUsers;
        const userIds = new Set<string>(
            this.activeStudentGroup?.userIds ||
                this.store.root.studentGroupStore.managedStudentGroups.flatMap((g) => [...g.userIds])
        );
        return [...userIds].filter((userId) => !editingStates[userId]);
    }
}
